@echo off
echo .  SOFTWARE INSTALLED IN THIS NETWORK:
echo .  컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
echo .  CIM          Comet 2
echo .  CWI          Comet 1 Chinese Word Processor
echo .  DBASE        dBase III+ ver 1.0
echo .  ET2          ETen Chinese System ver 2.2 (Big-5 code)
echo .  ETUTL        ETen System Utilities
echo .  ETRAS        ETen configured for PCRAS (ET code)
echo .  FLOW3        FlowCharting III
echo .  FOXL         FoxPro/LAN ver 2.0
echo .  HG3          Harvard Graphics ver 3.0
echo .  HAN254       Chun Hon Chinese System ver 2.54 (Big-5 code)
echo .  HANCATI      Chun Hon configured for CATI (ET code)
echo .  HOME         Back to my own data directory
echo .  L123         Lotus ver 2.2 Access System
echo .  123          Lotus ver 2.3 1-2-3
echo .  LOTUS        Lotus ver 2.3 Access System
echo .  MAIL         Electronic mail
echo .  NC           Norton Commander 3.0
@pause
echo .  NE           Norton Editor 1.3
echo .  NORTON       Norton Utilities ver 6.01
echo .  PCTOOLS      PCTools 4.30
echo .  PCBACKUP     PC Backup 6.0
echo .  PRIMELIN     Primelink 3.0
echo .  SHOWP        LIst print queue connected to LPT1..LPT3
echo .  WP           WordPerfect 5.1
echo .  XTPRO        XTree Professional ver 1.01
