#!/bin/sh
#
# DD-WRT :: View topic - save shell history
# https://forum.dd-wrt.com/phpBB2/viewtopic.php?t=311267
#
exe() { echo "# $@" ; "$@" ; }

function chkcrt() {
  #
  # $1 should not be prefixed by "https:\\", just domain name
  #
  echo | openssl s_client -connect $1:443 2> /dev/null | openssl x509 -noout -issuer -subject -dates
}

function ddver() {
  echo "DD-WRT v3.0-r$(nvram get os_version) $(nvram get dist_type) ($(grep Release /tmp/loginprompt | cut -d : -f 2 | tr -d ' '))"
  uname -a 
}

function gettime() {
  curl -I 'https://www.google.com/'  2>/dev/null | grep -i '^date:' | sed 's/^[Dd]ate: //g'
}

function gettime2() {
  gettime | awk 'BEGIN{months="JanFebMarAprMayJunJulAugSepOctNovDec"}{printf("%s%02d%s%s", $4, index(months,$3)/3+1,$2,$5)}' | sed 's/://' | sed 's/:/./'
}

function dnf() {
  opkg list | grep $1 | cut -d \  -f 1
}

function grepsrc() {
  echo Searching "$1"
  find /opt/DL/src/dd-wrt/src/router -type f -exec grep -n -H "$1" {} \;
}

export HISTCONTROL='ignoredups'
export HISTFILE='/opt/home/root/.ash_history'
export HISTSIZE='50' 

export LESS_TERMCAP_mb=$'\e[1;32m'
export LESS_TERMCAP_md=$'\e[1;32m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;4;31m'

export PAGER=more
# export MANPAGER='less -s -M +Gg'

alias rm="rm -i" 
alias cp="cp -i" 
alias mv="mv -i" 
#
alias ps="COLUMNS=132 ps"
alias vi="/opt/bin/vim"
alias dire="du -d 1 -h"

alias wlscan=" \
site_survey 2>&1 \
 | tail -n +2 \
 | sed -e 's/^./{/' \
-e 's/\] SSID\[/\} SSID\{/' \
-e 's/\] BSSID\[/} BSSID{/' \
-e 's/\] channel\[/} channel{/' \
-e 's/\] frequency\[/} frequency{/' \
-e 's/\] numsta\[/} numsta{/' \
-e 's/\] rssi\[/} rssi{/' \
-e 's/\] noise\[/} noise{/' \
-e 's/\] beacon\[/} beacon{/' \
-e 's/\] cap\[/} cap{/' \
-e 's/\] dtim\[/} dtim{/' \
-e 's/\] rate\[/} rate{/' \
-e 's/\] enc\[/} enc{/' \
-e 's/.$/\}/' \
 | cut -d \} -f 2,4 | sed -e 's/SSID{//' -e 's/} channel{/   /' \
"
alias scrcap='tmux capture-pane -p -S-'
#
# bash - How can I set my default shell to start up tmux - Unix & Linux Stack Exchange
# https://unix.stackexchange.com/questions/43601/how-can-i-set-my-default-shell-to-start-up-tmux
# 
# history -s "tmux attach"
#
# if [[ -z "$TMUX" ]]; then
#   exec tmux new-session -A -s default
#   exit
# fi
# if [[ -z "$TMUX" ]]; then
#    if tmux has-session 2>/dev/null; then
#        exec tmux attach -t default
#    else
#        exec tmux new -s default
#    fi
# fi
#
# if command -v tmux &> /dev/null && [ -n "$PS1" ] &&  [[ ! "$LAUNCHED" == "vscode" ]] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
#  exec tmux new-session -A -s main
# fi
#
# if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
#  tmux a -t default || exec tmux new -s default && exit;
# fi
